name = "quiver-bookings-api"
main = "worker.js"
compatibility_date = "2024-09-25"

[env.production]
routes = [
  { pattern = "quiver-bookings-api.kevingermishuys.workers.dev/*", zone_name = "kevingermishuys.workers.dev" }
]
